# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
           path: ${{ github.workspace }}
           fail-build: false
           acs-report-enable: true
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode clean install