# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
           path: ${{ github.workspace }}
           fail-build: false
           acs-report-enable: true

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven 1st time
        run: mvn --batch-mode clean install || exit 0

      - name: Hack iweb-modules in
        run: cp -R ./src/iweb-modules ./src/nics-web/modules/

      - name: Build with Maven 2nd time
        run: mvn --batch-mode clean install || exit 0